### ISSUE TITLE
Date editable

### ISSUE THREAD

**Issue by wearecrunch** [wearecrunch/Endeavour#1]
Make date editable for Blog Posts

**Comment by bogdanszabo** [comment]
Modified the database:
- table: `blogitem`
  - changed the column `timestamp` from `TYPE_INT` to `TYPE-DATE`

Modified two files:
- add the `array` for the the `date picker`: 8a980bb2c6f375b3a53662ed9f8d717aa32c6a29
- `timestamp` to `TYPE_DATE`, default date `today`, echo the date in other format: 1fcfdf388dd77bc586bfa188bb3fe2d4b712473a
